version: '3.8'
services:
  twitter:
    image: duonghuyhoang2003/twitter:${TAG} 
    ports:
      - '3002:3002'
    networks:
      - app-network

  # mongo:
  #   image: mongo:6
  #   container_name: mongo_db
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ./db/mongo_data:/data/db
  #   networks:
  #     - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - app-network

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
